import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
import {STLLoader} from 'three/addons/loaders/STLLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {OBJExporter} from 'three/addons/exporters/OBJExporter.js';
import {STLExporter} from 'three/addons/exporters/STLExporter.js';
import {mergeGeometries} from 'three/addons/utils/BufferGeometryUtils.js';
import {RectAreaLightUniformsLib} from 'three/addons/lights/RectAreaLightUniformsLib.js';
import {RectAreaLightHelper} from 'three/addons/helpers/RectAreaLightHelper.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const canvas=$('#viewport'), wrap=$('#viewportWrap'), outliner=$('#outliner'), props=$('#propertiesContent'), input=$('#fileInput');
const state={selected:null,selection:new Set(),tool:'translate',space:'world',multi:false,mode:'object',tab:'object',snap:false,shading:'solid',counter:1,bg:'#2b2d31',axes:true,shadows:true,blenderInfo:null,studioStrength:1,renderWidth:1920,renderHeight:1080,renderScale:1,renderTransparent:false,undo:[],redo:[],historyLock:false,editPoints:null,editHandle:null,editVertex:-1,editVertices:new Set(),editBase:new Map(),editCenter:new THREE.Vector3(),pointer:{x:0,y:0,moved:false}};
const scene=new THREE.Scene(); scene.background=new THREE.Color(state.bg);
const camera=new THREE.PerspectiveCamera(50,1,.01,5000); camera.position.set(7,5.5,8);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true,alpha:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.shadowMap.type=THREE.PCFSoftShadowMap; renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping; renderer.toneMappingExposure=1; RectAreaLightUniformsLib.init();
const pmrem=new THREE.PMREMGenerator(renderer); const studioEnv=pmrem.fromScene(new RoomEnvironment(),.04).texture;
const orbit=new OrbitControls(camera,canvas); orbit.enableDamping=true; orbit.target.set(0,.8,0); orbit.screenSpacePanning=true;
const transform=new TransformControls(camera,canvas); scene.add(transform.getHelper()); transform.getHelper().visible=false;
const grid=new THREE.GridHelper(100,100,0x55575c,0x3b3d42); grid.material.transparent=true; grid.material.opacity=.55; scene.add(grid);
const axes=new THREE.AxesHelper(1.3); axes.position.y=.002; scene.add(axes);
const editorHemi=new THREE.HemisphereLight(0xffffff,0x30384a,1.8); editorHemi.userData.editorLight=true; scene.add(editorHemi);
const editorSun=new THREE.DirectionalLight(0xffffff,2.25); editorSun.position.set(4,8,5); editorSun.castShadow=true; editorSun.shadow.mapSize.set(2048,2048); editorSun.shadow.camera.near=.1; editorSun.shadow.camera.far=60; editorSun.userData.editorLight=true; scene.add(editorSun);
const box=new THREE.BoxHelper(undefined,0xff9a36); box.visible=false; box.material.depthTest=false; scene.add(box);
const ray=new THREE.Raycaster(), pointer=new THREE.Vector2();
const editable=()=>scene.children.filter(o=>o.userData&&o.userData.editable);
const roots=()=>editable().filter(o=>!o.parent||!o.parent.userData||!o.parent.userData.editable);
const selected=()=>[...state.selection].filter(o=>o?.parent&&o.userData?.editable);
const sourceMaterials=new WeakMap(), solidOverrides=new WeakMap(), wireOverrides=new WeakMap();
const sourceMaterialOf=m=>sourceMaterials.get(m)||m.material;
function rememberMaterial(m){if(m?.isMesh&&!sourceMaterials.has(m))sourceMaterials.set(m,m.material)}
function rememberAllMaterials(){roots().forEach(o=>o.traverse(rememberMaterial))}
function restoreSourceMaterials(){roots().forEach(o=>o.traverse(m=>{if(m.isMesh&&sourceMaterials.has(m))m.material=sourceMaterials.get(m)}))}
function sceneLights(){return roots().filter(o=>o.userData?.kind==='light')}
function setSceneLightContribution(on){sceneLights().forEach(l=>{if(on){if('_viewportVisible' in l.userData){l.visible=l.userData._viewportVisible;delete l.userData._viewportVisible}}else if(!('_viewportVisible' in l.userData)){l.userData._viewportVisible=l.visible;l.visible=false}})}
function materialList(x){return Array.isArray(x)?x:[x]}
function applyViewportShading(mode=state.shading){state.shading=mode;rememberAllMaterials();restoreSourceMaterials();scene.environmentIntensity=state.studioStrength;editorHemi.visible=mode==='solid';editorSun.visible=mode==='solid';setSceneLightContribution(mode==='rendered');scene.environment=(mode==='solid'||mode==='material')?studioEnv:null;scene.background=new THREE.Color(state.bg);roots().forEach(o=>o.traverse(m=>{if(!m.isMesh)return;if(mode==='solid'){let x=solidOverrides.get(m);if(!x){x=new THREE.MeshStandardMaterial({color:0x8d9096,roughness:.62,metalness:0});solidOverrides.set(m,x)}m.material=x}else if(mode==='wire'){let x=wireOverrides.get(m);if(!x){x=new THREE.MeshBasicMaterial({color:0xc2c6cf,wireframe:true,transparent:true,opacity:.92});wireOverrides.set(m,x)}m.material=x}}));$('.shade').forEach(b=>b.classList.toggle('active',b.dataset.shading===mode));status(({solid:'Solid studio shading',material:'Material Preview',wire:'Wireframe',rendered:'Rendered viewport'})[mode]||mode)}
const mat=(c='#9aa0a8')=>new THREE.MeshStandardMaterial({color:c,roughness:.55,metalness:.05});
const toast=m=>{let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1400)};
const status=m=>$('#statusText').textContent=m;
const dl=(b,n)=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
const BLEND_PARSER_URL='https://cdn.jsdelivr.net/npm/jsblender@0.0.4/+esm';
const BLENDER_TO_THREE=new THREE.Matrix4().makeRotationX(-Math.PI/2), THREE_TO_BLENDER=BLENDER_TO_THREE.clone().invert();
let blendParserPromise=null;
const getBlendParser=()=>blendParserPromise||(blendParserPromise=import(BLEND_PARSER_URL));

function helperFor(o){return o&&o.userData.helperUUID?scene.getObjectByProperty('uuid',o.userData.helperUUID):null}
function addPrimitive(type,opt={}){
 let g; if(type==='Sphere')g=new THREE.SphereGeometry(1.2,32,20);else if(type==='Cylinder')g=new THREE.CylinderGeometry(1,1,2.3,32);else if(type==='Cone')g=new THREE.ConeGeometry(1.2,2.5,32);else if(type==='Torus')g=new THREE.TorusGeometry(1.25,.38,18,48);else if(type==='Torus Knot')g=new THREE.TorusKnotGeometry(1,.3,96,14);else if(type==='Plane')g=new THREE.PlaneGeometry(3,3,8,8);else if(type==='Circle')g=new THREE.CircleGeometry(1.5,48);else g=new THREE.BoxGeometry(2,2,2);
 const o=new THREE.Mesh(g,mat(opt.color||'#9aa0a8')); o.name=opt.name||type+'.'+String(state.counter++).padStart(3,'0'); o.userData={editable:true,kind:'mesh'}; o.castShadow=type!=='Plane'&&type!=='Circle';o.receiveShadow=true;if(type==='Plane'||type==='Circle')o.rotation.x=-Math.PI/2;o.position.copy(orbit.target);if(opt.position)o.position.fromArray(opt.position);scene.add(o);rememberMaterial(o);select(o);applyViewportShading();push('Add '+type);renderOutliner();stats();return o
}
function addLight(type){
 let l=type==='Point Light'?new THREE.PointLight(0xffffff,30,25,2):type==='Spot Light'?new THREE.SpotLight(0xffffff,45,35,Math.PI/5,.35,2):new THREE.DirectionalLight(0xffffff,2);
 l.name=type+'.'+String(state.counter++).padStart(3,'0');l.position.copy(camera.position).lerp(orbit.target,.35);l.userData={editable:true,kind:'light'};l.castShadow=true;scene.add(l);
 const h=type==='Point Light'?new THREE.PointLightHelper(l,.3):type==='Spot Light'?new THREE.SpotLightHelper(l):new THREE.DirectionalLightHelper(l,.7);h.userData.editorHelper=true;l.userData.helperUUID=h.uuid;scene.add(h);select(l);applyViewportShading();push('Add '+type);renderOutliner();stats()
}
function addEmpty(){const o=new THREE.Group();o.name='Empty.'+String(state.counter++).padStart(3,'0');o.userData={editable:true,kind:'empty'};o.position.copy(orbit.target);o.add(new THREE.AxesHelper(.65));scene.add(o);select(o);push('Add Empty');renderOutliner();stats()}
function addCamera(){const o=new THREE.PerspectiveCamera(50,1.777,.1,100);o.name='Camera.'+String(state.counter++).padStart(3,'0');o.userData={editable:true,kind:'camera'};o.position.copy(camera.position);o.quaternion.copy(camera.quaternion);scene.add(o);const h=new THREE.CameraHelper(o);h.userData.editorHelper=true;o.userData.helperUUID=h.uuid;scene.add(h);select(o);push('Add Camera');renderOutliner();stats()}

function select(o,{add=false,toggle=false}={}){
 if(state.mode==='edit'&&o!==state.selected)exitEdit(false);
 if(!add)state.selection.clear();
 if(o){
  if(toggle&&state.selection.has(o)){state.selection.delete(o);if(state.selected===o)state.selected=selected().at(-1)||null}
  else{state.selection.add(o);state.selected=o}
 }else if(!add)state.selected=null;
 if(state.selected&&!state.selection.has(state.selected))state.selected=selected().at(-1)||null;
 const a=state.selected;
 if(a){transform.attach(a);transform.setMode(state.tool==='select'?'translate':state.tool);transform.setSpace(state.space);transform.getHelper().visible=state.tool!=='select';box.setFromObject(a);box.visible=state.mode==='object'&&a.userData.kind==='mesh';status(selected().length>1?selected().length+' objects selected':'Selected '+a.name)}
 else{transform.detach();transform.getHelper().visible=false;box.visible=false}
 renderOutliner();renderProps()
}
function selectAll(){if(state.mode==='edit')return selectAllVerts();state.selection=new Set(roots().filter(o=>o.visible));state.selected=selected().at(-1)||null;select(state.selected,{add:true})}
function deselectAll(){if(state.mode==='edit')return deselectVerts();state.selection.clear();state.selected=null;select(null)}
function icon(o){return o.userData.kind==='light'?'✦':o.userData.kind==='camera'?'△':o.userData.kind==='empty'?'⌗':'◆'}
function renderOutliner(target=outliner){
 target.innerHTML='';roots().forEach(o=>{const r=document.createElement('div');r.className='outliner-row'+(state.selection.has(o)?' selected':'')+(o===state.selected?' active':'');r.innerHTML='<span class="type">'+icon(o)+'</span><span class="name"></span><button class="visibility">'+(o.visible?'◉':'○')+'</button>';$('.name',r).textContent=o.name;r.onclick=e=>{if(!e.target.closest('.visibility')){const add=e.shiftKey||state.multi;select(o,{add,toggle:add})}};$('.visibility',r).onclick=e=>{e.stopPropagation();o.visible=!o.visible;e.currentTarget.textContent=o.visible?'◉':'○'};target.appendChild(r)});
 if(!target.children.length)target.innerHTML='<div class="empty-state">Scene is empty.<br>Use <b>＋ Add</b>.</div>'
}
function xyz(title,v,cb,step=.01){const s=document.createElement('div');s.className='section';s.innerHTML='<div class="section-title">'+title+'</div><div class="xyz-row"></div>';['x','y','z'].forEach((a,i)=>{const l=document.createElement('label');l.className='xyz-field '+a;l.innerHTML='<span>'+a.toUpperCase()+'</span><input type="number" step="'+step+'" value="'+Number(v[i].toFixed(4))+'">';$('input',l).onchange=e=>cb(i,+e.target.value);$('.xyz-row',s).appendChild(l)});return s}
function renderProps(target=props,tab=state.tab){
 target.innerHTML='';if(tab==='scene'){renderScene(target);return}const o=state.selected;if(!o){target.innerHTML='<div class="empty-state">Select an object.</div>';return}
 if(tab==='material'){renderMaterial(target,o);return}
 if(state.mode==='edit'){const e=document.createElement('div');e.className='section';e.innerHTML='<div class="section-title">Mesh Edit</div><div class="selection-summary">'+state.editVertices.size+' selected / '+(o.geometry?.attributes.position?.count||0)+' vertices</div><div class="action-row"><button class="allv">Select All</button><button class="nonev">Deselect</button><button class="collapsev">Collapse</button></div><div class="help-copy">Tap a vertex to select it. Hold Shift, or enable ±, to add/remove vertices. Drag the gizmo to move the selected vertex set.</div>';$('.allv',e).onclick=selectAllVerts;$('.nonev',e).onclick=deselectVerts;$('.collapsev',e).onclick=collapseVerts;target.appendChild(e);return}
 const a=document.createElement('div');a.className='section';a.innerHTML='<div class="section-title">Object'+(selected().length>1?' • '+selected().length+' selected':'')+'</div><label class="field-row"><span>Name</span><input class="nm"></label><div class="action-row"><button class="frame">Frame</button><button class="dup">Duplicate</button><button class="hide">Hide</button></div>';$('.nm',a).value=o.name;$('.nm',a).onchange=e=>{o.name=e.target.value||'Object';renderOutliner();push('Rename')};$('.frame',a).onclick=frame;$('.dup',a).onclick=duplicate;$('.hide',a).onclick=hideSelected;target.appendChild(a);
 target.appendChild(xyz('Location',o.position.toArray(),(i,v)=>{o.position.setComponent(i,v);changed()}));
 target.appendChild(xyz('Rotation',[o.rotation.x,o.rotation.y,o.rotation.z].map(THREE.MathUtils.radToDeg),(i,v)=>{o.rotation[['x','y','z'][i]]=THREE.MathUtils.degToRad(v);changed()},.1));
 target.appendChild(xyz('Scale',o.scale.toArray(),(i,v)=>{o.scale.setComponent(i,v);changed()}));
 const t=document.createElement('div');t.className='section';t.innerHTML='<div class="section-title">Transform & Mesh</div><div class="field-row"><span>Gizmo space</span><button class="wide-btn space">'+(state.space==='world'?'World':'Local')+'</button></div><div class="action-row"><button class="apply">Apply Transform</button><button class="origin">Origin to Geometry</button><button class="smooth">Shade Smooth</button><button class="flat">Shade Flat</button></div>'+(selected().length>1?'<div style="height:5px"></div><button class="wide-btn join">Join Selected Meshes (Ctrl+J)</button>':'');$('.space',t).onclick=toggleSpace;$('.apply',t).onclick=applyTransforms;$('.origin',t).onclick=originToGeometry;$('.smooth',t).onclick=()=>shade(true);$('.flat',t).onclick=()=>shade(false);$('.join',t)?.addEventListener('click',joinSelected);target.appendChild(t);
 if(o.userData.kind==='light'){const l=document.createElement('div');l.className='section';l.innerHTML='<div class="section-title">Light</div><label class="field-row"><span>Color</span><input class="lc" type="color" value="#'+o.color.getHexString()+'"></label><label class="field-row"><span>Intensity</span><input class="li" type="number" step=".1" value="'+o.intensity+'"></label>';$('.lc',l).oninput=e=>o.color.set(e.target.value);$('.li',l).onchange=e=>o.intensity=+e.target.value;target.appendChild(l)}
}
function renderMaterial(target,o){let m; o.traverse(c=>{if(!m&&c.isMesh){rememberMaterial(c);const sm=sourceMaterialOf(c);m=Array.isArray(sm)?sm[0]:sm}});if(!m){target.innerHTML='<div class="empty-state">No mesh material.</div>';return}const s=document.createElement('div');s.className='section';s.innerHTML='<div class="section-title">Surface</div><label class="field-row"><span>Base Color</span><input class="c" type="color" value="#'+(m.color?m.color.getHexString():'ffffff')+'"></label><label class="field-row"><span>Metallic</span><input class="metal" type="range" min="0" max="1" step=".01" value="'+(m.metalness||0)+'"></label><label class="field-row"><span>Roughness</span><input class="rough" type="range" min="0" max="1" step=".01" value="'+(m.roughness==null?.5:m.roughness)+'"></label><label class="field-row"><span>Opacity</span><input class="alpha" type="range" min=".05" max="1" step=".01" value="'+(m.opacity||1)+'"></label><label class="checkbox-row"><input class="wire" type="checkbox" '+(m.wireframe?'checked':'')+'> Wireframe</label>';$('.c',s).oninput=e=>m.color&&m.color.set(e.target.value);$('.metal',s).oninput=e=>{if('metalness'in m)m.metalness=+e.target.value};$('.rough',s).oninput=e=>{if('roughness'in m)m.roughness=+e.target.value};$('.alpha',s).oninput=e=>{m.opacity=+e.target.value;m.transparent=m.opacity<1};$('.wire',s).onchange=e=>m.wireframe=e.target.checked;target.appendChild(s);const t=document.createElement('div');t.className='section';t.innerHTML='<div class="section-title">Texture</div><button class="wide-btn tex">Load Image Texture…</button><div style="height:5px"></div><button class="wide-btn clear">Clear Texture</button>';$('.tex',t).onclick=()=>pick('image/*',fs=>loadTexture(fs[0],m));$('.clear',t).onclick=()=>{m.map=null;m.needsUpdate=true};target.appendChild(t)}
function renderScene(target){
 const s=document.createElement('div');s.className='section';s.innerHTML='<div class="section-title">World & Viewport</div><label class="field-row"><span>Background</span><input class="bg" type="color" value="'+state.bg+'"></label><label class="field-row"><span>Exposure</span><input class="ex" type="number" step=".05" value="'+renderer.toneMappingExposure+'"></label><label class="field-row"><span>Studio Strength</span><input class="env" type="range" min="0" max="2" step=".05" value="'+state.studioStrength+'"></label><label class="checkbox-row"><input class="gr" type="checkbox" '+(grid.visible?'checked':'')+'> Show grid</label><label class="checkbox-row"><input class="ax" type="checkbox" '+(axes.visible?'checked':'')+'> Show world axes</label><label class="checkbox-row"><input class="sh" type="checkbox" '+(state.shadows?'checked':'')+'> Soft viewport shadows</label>';$('.bg',s).oninput=e=>{state.bg=e.target.value;scene.background.set(state.bg)};$('.ex',s).onchange=e=>renderer.toneMappingExposure=+e.target.value;$('.env',s).oninput=e=>{state.studioStrength=+e.target.value;scene.environmentIntensity=state.studioStrength};$('.gr',s).onchange=e=>grid.visible=e.target.checked;$('.ax',s).onchange=e=>{state.axes=e.target.checked;axes.visible=state.axes};$('.sh',s).onchange=e=>{state.shadows=e.target.checked;renderer.shadowMap.enabled=state.shadows};target.appendChild(s);
 if(state.blenderInfo){const b=document.createElement('div');b.className='section';b.innerHTML='<div class="section-title">Blender Source</div><div class="field-row"><span>File</span><strong class="bf"></strong></div><div class="field-row"><span>Version</span><strong class="bv"></strong></div><div class="field-row"><span>Scene</span><strong class="bs"></strong></div><div class="field-row"><span>Imported</span><strong class="bo"></strong></div><div class="field-row"><span>Timeline</span><strong class="bt"></strong></div><div class="help-copy">Direct .blend import currently targets Blender 5.x. Meshes, transforms, basic materials, lights, cameras, empties, custom properties, scene metadata, and supported Mirror/Array modifiers are brought into BlendWeb.</div>';$('.bf',b).textContent=state.blenderInfo.file||'';$('.bv',b).textContent=state.blenderInfo.version||'';$('.bs',b).textContent=state.blenderInfo.scene||'Scene';$('.bo',b).textContent=(state.blenderInfo.objects||0)+' objects';$('.bt',b).textContent=state.blenderInfo.frames||'—';target.appendChild(b)}
 const st=document.createElement('div');st.className='section';st.innerHTML='<div class="section-title">Scene Tools</div><div class="action-row"><button class="all">Select All</button><button class="none">Deselect</button><button class="show">Unhide All</button></div>';$('.all',st).onclick=selectAll;$('.none',st).onclick=deselectAll;$('.show',st).onclick=unhideAll;target.appendChild(st);const rr=document.createElement('div');rr.className='section';rr.innerHTML='<div class="section-title">Render</div><label class="field-row"><span>Width</span><input class="rw" type="number" min="64" max="8192" step="1" value="'+state.renderWidth+'"></label><label class="field-row"><span>Height</span><input class="rh" type="number" min="64" max="8192" step="1" value="'+state.renderHeight+'"></label><label class="field-row"><span>Supersample</span><select class="rs"><option value="1">1×</option><option value="2">2×</option><option value="3">3×</option></select></label><label class="checkbox-row"><input class="rt" type="checkbox" '+(state.renderTransparent?'checked':'')+'> Transparent background</label><button class="wide-btn render-now">Render PNG</button><div class="help-copy">Rendered mode uses the scene materials and actual scene lights. Solid and Material Preview use Blender-style studio/environment lighting.</div>';$('.rw',rr).onchange=e=>state.renderWidth=Math.max(64,Math.min(8192,+e.target.value||1920));$('.rh',rr).onchange=e=>state.renderHeight=Math.max(64,Math.min(8192,+e.target.value||1080));$('.rs',rr).value=String(state.renderScale);$('.rs',rr).onchange=e=>state.renderScale=+e.target.value;$('.rt',rr).onchange=e=>state.renderTransparent=e.target.checked;$('.render-now',rr).onclick=renderImage;target.appendChild(rr);
 const p=document.createElement('div');p.className='section';p.innerHTML='<div class="section-title">Project</div><div class="action-row"><button class="new">New</button><button class="save">Save File</button><button class="open">Open File</button><button class="blend">Import .blend</button></div>';$('.new',p).onclick=newProject;$('.save',p).onclick=saveProject;$('.open',p).onclick=()=>pick('.blendweb,.json',fs=>loadProject(fs[0]));$('.blend',p).onclick=()=>pick('.blend',fs=>importBlendProject(fs[0]));target.appendChild(p)
}
function refreshEdit(){
 const o=state.selected;if(!o||!state.editHandle||!state.editVertices.size){transform.detach();transform.getHelper().visible=false;renderProps();return}
 const a=o.geometry.attributes.position,c=new THREE.Vector3();state.editBase=new Map();
 for(const i of state.editVertices){const v=new THREE.Vector3().fromBufferAttribute(a,i);state.editBase.set(i,v.clone());c.add(v)}
 c.multiplyScalar(1/state.editVertices.size);state.editCenter.copy(c);state.editHandle.position.copy(o.localToWorld(c.clone()));state.editHandle.quaternion.identity();state.editHandle.scale.set(1,1,1);transform.attach(state.editHandle);transform.setMode('translate');transform.setSpace('world');transform.getHelper().visible=true;state.editVertex=[...state.editVertices][0]??-1;status(state.editVertices.size+' vert'+(state.editVertices.size===1?'':'s')+' selected');renderProps()
}
function enterEdit(){const o=state.selected;if(!o||!o.isMesh||!o.geometry.attributes.position){toast('Select a mesh first');return}if(selected().length>1){state.selection=new Set([o]);renderOutliner()}state.mode='edit';$('#modeBtn').textContent='Edit Mode ▾';transform.detach();box.visible=false;state.editPoints=new THREE.Points(o.geometry,new THREE.PointsMaterial({color:0xff9a36,size:.095,sizeAttenuation:true,depthTest:false}));state.editPoints.userData.editorHelper=true;o.add(state.editPoints);state.editHandle=new THREE.Object3D();scene.add(state.editHandle);state.editVertex=-1;state.editVertices.clear();state.editBase.clear();setTool('translate');status('Edit Mode: tap vertices, Shift or ± adds/removes');renderProps()}
function exitEdit(hist=true){if(state.mode!=='edit')return;if(state.editPoints?.parent){state.editPoints.parent.remove(state.editPoints);state.editPoints.material?.dispose?.()}if(state.editHandle)scene.remove(state.editHandle);state.editPoints=null;state.editHandle=null;state.editVertex=-1;state.editVertices.clear();state.editBase.clear();state.mode='object';$('#modeBtn').textContent='Object Mode ▾';if(state.selected)select(state.selected);if(hist)push('Edit mesh')}
function toggleEdit(){state.mode==='edit'?exitEdit():enterEdit()}
function selectVertex(x,y,add=false){const o=state.selected;if(!o||!state.editPoints)return;const r=canvas.getBoundingClientRect();pointer.x=((x-r.left)/r.width)*2-1;pointer.y=-((y-r.top)/r.height)*2+1;ray.setFromCamera(pointer,camera);ray.params.Points.threshold=Math.max(.06,camera.position.distanceTo(orbit.target)*.008);const h=ray.intersectObject(state.editPoints,false)[0];if(!h){if(!add)deselectVerts();return}if(!add)state.editVertices.clear();if(add&&state.editVertices.has(h.index))state.editVertices.delete(h.index);else state.editVertices.add(h.index);refreshEdit()}
function selectAllVerts(){if(state.mode!=='edit')return;const n=state.selected.geometry.attributes.position.count;state.editVertices=new Set(Array.from({length:n},(_,i)=>i));refreshEdit()}
function deselectVerts(){state.editVertices.clear();state.editVertex=-1;transform.detach();transform.getHelper().visible=false;renderProps();status('No vertices selected')}
function collapseVerts(){if(state.mode!=='edit'||state.editVertices.size<2){toast('Select at least 2 vertices');return}const o=state.selected,a=o.geometry.attributes.position,c=new THREE.Vector3();for(const i of state.editVertices)c.add(new THREE.Vector3().fromBufferAttribute(a,i));c.multiplyScalar(1/state.editVertices.size);for(const i of state.editVertices)a.setXYZ(i,c.x,c.y,c.z);a.needsUpdate=true;o.geometry.computeVertexNormals();o.geometry.computeBoundingSphere();refreshEdit();push('Collapse vertices');stats()}
function beginEditMove(){if(state.mode!=='edit'||!state.editVertices.size)return;const o=state.selected,a=o.geometry.attributes.position,c=new THREE.Vector3();state.editBase=new Map();for(const i of state.editVertices){const v=new THREE.Vector3().fromBufferAttribute(a,i);state.editBase.set(i,v.clone());c.add(v)}c.multiplyScalar(1/state.editVertices.size);state.editCenter.copy(c)}
function updateVertex(){if(state.mode!=='edit'||!state.editVertices.size)return;const o=state.selected,a=o.geometry.attributes.position,cur=o.worldToLocal(state.editHandle.position.clone()),d=cur.clone().sub(state.editCenter);for(const [i,b] of state.editBase){const v=b.clone().add(d);a.setXYZ(i,v.x,v.y,v.z)}a.needsUpdate=true;o.geometry.computeVertexNormals();o.geometry.computeBoundingSphere()}

function setTool(t){state.tool=t;$$('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));if(t==='select'){transform.detach();transform.getHelper().visible=false}else if(state.mode==='edit'){if(state.editVertices.size){transform.attach(state.editHandle);transform.setMode('translate');transform.setSpace('world');transform.getHelper().visible=true}}else if(state.selected){transform.attach(state.selected);transform.setMode(t);transform.setSpace(state.space);transform.getHelper().visible=true}$('#transformModeText').textContent=state.mode==='edit'?'Vertex Edit • '+state.editVertices.size:t[0].toUpperCase()+t.slice(1)+' • '+state.space}
function changed(){box.update();helperFor(state.selected)?.update?.();renderProps();debouncedPush()}
let ht;function debouncedPush(){clearTimeout(ht);ht=setTimeout(()=>push('Transform'),220)}
function snap(){state.snap=!state.snap;$('#snapBtn').classList.toggle('active',state.snap);transform.setTranslationSnap(state.snap?.25:null);transform.setRotationSnap(state.snap?THREE.MathUtils.degToRad(15):null);transform.setScaleSnap(state.snap?.1:null)}
function view(v){const t=orbit.target.clone(),d=Math.max(6,camera.position.distanceTo(t));if(v==='top')camera.position.set(t.x,t.y+d,t.z+.001);else if(v==='front')camera.position.set(t.x,t.y,t.z+d);else if(v==='right')camera.position.set(t.x+d,t.y,t.z);else camera.position.set(t.x+d*.7,t.y+d*.5,t.z+d*.8);camera.lookAt(t);orbit.update()}
function frame(){const os=selected();if(!os.length)return;const b=new THREE.Box3();os.forEach(o=>b.expandByObject(o));const c=b.getCenter(new THREE.Vector3()),sz=b.getSize(new THREE.Vector3()).length()||2,d=camera.position.clone().sub(orbit.target).normalize();orbit.target.copy(c);camera.position.copy(c).add(d.multiplyScalar(Math.max(2.5,sz*1.7)));orbit.update()}
function stats(){let v=0;editable().forEach(o=>o.traverse(c=>{if(c.isMesh)v+=c.geometry.attributes.position?.count||0}));$('#sceneStats').textContent=editable().length+' objects • '+v.toLocaleString()+' verts'}
function duplicate(){const os=selected();if(!os.length)return;const mode=state.shading;restoreSourceMaterials();const cs=os.map(o=>{const c=o.clone(true);c.name=o.name.replace(/\.\d+$/,'')+'.'+String(state.counter++).padStart(3,'0');c.position.x+=.5;c.userData={...o.userData,editable:true};delete c.userData.helperUUID;scene.add(c);return c});rememberAllMaterials();applyViewportShading(mode);state.selection=new Set(cs);state.selected=cs.at(-1)||null;select(state.selected,{add:true});push('Duplicate');renderOutliner();stats()}
function removeOne(o){const h=helperFor(o);if(h)scene.remove(h);scene.remove(o)}
function remove(){const os=selected();if(!os.length)return;if(state.mode==='edit')exitEdit(false);state.selection.clear();state.selected=null;transform.detach();box.visible=false;os.forEach(removeOne);push('Delete objects');renderOutliner();renderProps();stats();toast(os.length+' object'+(os.length===1?'':'s')+' deleted')}
function hideSelected(){const os=selected();if(!os.length)return;os.forEach(o=>o.visible=false);deselectAll();push('Hide objects');toast(os.length+' hidden')}
function unhideAll(){roots().forEach(o=>o.visible=true);renderOutliner();push('Unhide all');toast('All objects visible')}
function toggleSpace(){state.space=state.space==='world'?'local':'world';transform.setSpace(state.space);if($('#spaceBtn'))$('#spaceBtn').textContent=state.space==='world'?'W':'L';renderProps();setTool(state.tool);toast((state.space==='world'?'World':'Local')+' transform space')}
function applyTransforms(){const os=selected().filter(o=>o.isMesh);if(!os.length){toast('Select mesh objects');return}os.forEach(o=>{o.updateMatrix();o.geometry.applyMatrix4(o.matrix);o.position.set(0,0,0);o.rotation.set(0,0,0);o.scale.set(1,1,1);o.geometry.computeBoundingBox();o.geometry.computeBoundingSphere()});box.update();renderProps();push('Apply transforms');toast('Transforms applied')}
function originToGeometry(){const os=selected().filter(o=>o.isMesh);if(!os.length){toast('Select mesh objects');return}scene.updateMatrixWorld(true);os.forEach(o=>{o.geometry.computeBoundingBox();const c=o.geometry.boundingBox.getCenter(new THREE.Vector3()),w=o.localToWorld(c.clone());o.geometry.translate(-c.x,-c.y,-c.z);o.position.copy(o.parent.worldToLocal(w.clone()));o.geometry.computeBoundingBox();o.geometry.computeBoundingSphere()});box.update();renderProps();push('Origin to geometry');toast('Origins centered')}
function shade(smooth=true){const os=selected();if(!os.length)return;os.forEach(o=>o.traverse(c=>{if(!c.isMesh)return;rememberMaterial(c);c.geometry.computeVertexNormals();materialList(sourceMaterialOf(c)).forEach(m=>{if(m){m.flatShading=!smooth;m.needsUpdate=true}})}));applyViewportShading();push(smooth?'Shade smooth':'Shade flat');toast(smooth?'Smooth shading':'Flat shading')}
function worldGeo(m){let g=m.geometry.clone();if(g.index)g=g.toNonIndexed();if(!g.attributes.normal)g.computeVertexNormals();for(const n of Object.keys(g.attributes))if(n!=='position'&&n!=='normal')g.deleteAttribute(n);g.applyMatrix4(m.matrixWorld);g.computeVertexNormals();return g}
function joinSelected(){const os=selected();if(os.length<2){toast('Select at least 2 objects');return}scene.updateMatrixWorld(true);const ms=[];os.forEach(o=>o.traverse(c=>c.isMesh&&ms.push(c)));if(ms.length<2){toast('Need at least 2 meshes');return}let gs=ms.map(worldGeo),g;try{g=mergeGeometries(gs,false)}catch(e){console.error(e)}gs.forEach(x=>x.dispose());if(!g){toast('Could not join these meshes');return}rememberMaterial(ms[0]);const sm=sourceMaterialOf(ms[0]),fm=Array.isArray(sm)?sm[0]:sm,m=fm?.clone?.()||mat();const j=new THREE.Mesh(g,m);j.name='Joined.'+String(state.counter++).padStart(3,'0');j.userData={editable:true,kind:'mesh'};j.castShadow=j.receiveShadow=true;state.selection.clear();state.selected=null;os.forEach(removeOne);scene.add(j);rememberMaterial(j);select(j);applyViewportShading();push('Join meshes');renderOutliner();stats();frame();toast(ms.length+' meshes joined')}
function project(){rememberAllMaterials();restoreSourceMaterials();const data={app:'BlendWeb',version:4,scene:roots().map(o=>o.toJSON()),camera:{position:camera.position.toArray(),target:orbit.target.toArray()},world:{background:state.bg,exposure:renderer.toneMappingExposure,grid:grid.visible,axes:axes.visible,shadows:state.shadows,studioStrength:state.studioStrength},render:{width:state.renderWidth,height:state.renderHeight,scale:state.renderScale,transparent:state.renderTransparent},blenderInfo:state.blenderInfo};applyViewportShading();return data}
function restore(data,hist=false){state.historyLock=true;try{if(state.mode==='edit')exitEdit(false);state.selection.clear();state.selected=null;select(null);roots().forEach(o=>scene.remove(o));const loader=new THREE.ObjectLoader();(data.scene||[]).forEach(j=>{const o=loader.parse(j);o.userData.editable=true;o.traverse(c=>{if(c.isMesh){c.castShadow=true;c.receiveShadow=true}});scene.add(o)});if(data.camera){camera.position.fromArray(data.camera.position);orbit.target.fromArray(data.camera.target)}if(data.world){state.bg=data.world.background||state.bg;scene.background.set(state.bg);renderer.toneMappingExposure=data.world.exposure||1;grid.visible=data.world.grid!==false;state.axes=data.world.axes!==false;axes.visible=state.axes;state.shadows=data.world.shadows!==false;renderer.shadowMap.enabled=state.shadows;state.studioStrength=data.world.studioStrength??1}if(data.render){state.renderWidth=data.render.width||1920;state.renderHeight=data.render.height||1080;state.renderScale=data.render.scale||1;state.renderTransparent=!!data.render.transparent}state.blenderInfo=data.blenderInfo||null;sourceMaterials.clear?.();rememberAllMaterials();applyViewportShading();renderOutliner();renderProps();stats();orbit.update()}finally{state.historyLock=false}if(hist)push('Open project')}
function push(label){if(state.historyLock)return;const d=JSON.stringify(project());if(state.undo.at(-1)?.data===d)return;state.undo.push({label,data:d});if(state.undo.length>30)state.undo.shift();state.redo=[];localStorage.setItem('blendweb-autosave',d);buttons()}
function buttons(){$('#undoBtn').disabled=state.undo.length<2;$('#redoBtn').disabled=!state.redo.length}
function undo(){if(state.undo.length<2)return;state.redo.push(state.undo.pop());restore(JSON.parse(state.undo.at(-1).data));buttons()}
function redo(){const n=state.redo.pop();if(!n)return;state.undo.push(n);restore(JSON.parse(n.data));buttons()}
function saveProject(){dl(new Blob([JSON.stringify(project(),null,2)],{type:'application/json'}),'project.blendweb')}
function loadProject(f){const r=new FileReader();r.onload=()=>{try{restore(JSON.parse(r.result),true);toast('Project opened')}catch(e){console.error(e);toast('Open failed')}};r.readAsText(f)}
function newProject(){if(editable().length&&!confirm('Clear the current scene?'))return;roots().forEach(o=>scene.remove(o));state.undo=[];state.redo=[];state.blenderInfo=null;const c=addPrimitive('Cube',{name:'Cube',position:[0,1,0]});select(c);push('New project');frame()}
function pick(accept,fn,m=false){input.value='';input.accept=accept;input.multiple=m;input.onchange=()=>input.files?.length&&fn([...input.files]);input.click()}
function loadTexture(f,m){const r=new FileReader();r.onload=()=>new THREE.TextureLoader().load(r.result,t=>{t.colorSpace=THREE.SRGBColorSpace;m.map=t;m.needsUpdate=true});r.readAsDataURL(f)}
function safeBlendValue(v){if(typeof v==='bigint')return v.toString();if(Array.isArray(v))return v.map(safeBlendValue);if(v&&typeof v==='object'){const o={};for(const [k,x] of Object.entries(v))o[k]=safeBlendValue(x);return o}return v}
function blendTransform(obj,worldMatrix){const m=BLENDER_TO_THREE.clone().multiply(new THREE.Matrix4().fromArray(Array.from(worldMatrix))).multiply(THREE_TO_BLENDER);m.decompose(obj.position,obj.quaternion,obj.scale);obj.updateMatrix()}
function blendMaterial(d){const c=d?.diffuse||[.6,.6,.6,1],a=Number.isFinite(c[3])?THREE.MathUtils.clamp(c[3],0,1):1,m=new THREE.MeshStandardMaterial({roughness:Number.isFinite(d?.roughness)?THREE.MathUtils.clamp(d.roughness,0,1):.5,metalness:Number.isFinite(d?.metallic)?THREE.MathUtils.clamp(d.metallic,0,1):0,opacity:a,transparent:a<.999});m.color.setRGB(THREE.MathUtils.clamp(c[0]??.6,0,1),THREE.MathUtils.clamp(c[1]??.6,0,1),THREE.MathUtils.clamp(c[2]??.6,0,1));m.name=d?.name||'Blender Material';m.userData={source:'blend',hasNodeTree:!!d?.hasNodeTree};return m}
function blendGeometry(d){
 const g=new THREE.BufferGeometry(),fc=d.faceOffsets?.length?d.faceOffsets.length-1:0,triCount=Math.max(0,d.triangles?.length/3||0),pos=new Float32Array(triCount*9),nor=new Float32Array(triCount*9),uvNames=Object.keys(d.uvMaps||{}),uvSrc=uvNames.length?d.uvMaps[uvNames[0]]:null,uv=uvSrc?new Float32Array(triCount*6):null;let p=0,n=0,u=0,draw=0;
 for(let f=0;f<fc;f++){const start=d.faceOffsets[f]||0,end=d.faceOffsets[f+1]||start,size=end-start,faceStart=draw;if(size<3)continue;for(let k=1;k<size-1;k++){for(const ci of [start,start+k,start+k+1]){const vi=d.cornerVertices[ci]||0,vo=vi*3;pos[p++]=d.vertices[vo]||0;pos[p++]=d.vertices[vo+1]||0;pos[p++]=d.vertices[vo+2]||0;nor[n++]=d.vertexNormals?.[vo]||0;nor[n++]=d.vertexNormals?.[vo+1]||0;nor[n++]=d.vertexNormals?.[vo+2]||0;if(uv){const q=ci*2;uv[u++]=uvSrc[q]||0;uv[u++]=uvSrc[q+1]||0}draw++}}const count=draw-faceStart;if(count)g.addGroup(faceStart,count,d.materialIndices?.[f]||0)}
 g.setAttribute('position',new THREE.BufferAttribute(pos,3));g.setAttribute('normal',new THREE.BufferAttribute(nor,3));if(uv)g.setAttribute('uv',new THREE.BufferAttribute(uv,2));g.applyMatrix4(BLENDER_TO_THREE);if(!d.vertexNormals?.length)g.computeVertexNormals();g.computeBoundingBox();g.computeBoundingSphere();return g
}
function blendMaterialsFor(d,materialMap){let max=0;for(const x of d.materialIndices||[])max=Math.max(max,x||0);const count=Math.max(1,d.materialSlotNames?.length||0,max+1),a=[];for(let i=0;i<count;i++){const name=d.materialSlotNames?.[i],src=name?materialMap.get(name):null;a.push(src?blendMaterial(src):mat())}return a}
function collectionPathMap(root,map=new Map(),prefix=''){if(!root)return map;const here=prefix?prefix+'/'+root.name:root.name;for(const n of root.objectNames||[]){const a=map.get(n)||[];a.push(here);map.set(n,a)}for(const c of root.children||[])collectionPathMap(c,map,here);return map}
function blendLight(d){
 const color=new THREE.Color().setRGB(d?.color?.[0]??1,d?.color?.[1]??1,d?.color?.[2]??1),energy=Math.max(.001,d?.energy||1);let l;
 if(d?.type==='sun')l=new THREE.DirectionalLight(color,energy);
 else if(d?.type==='spot')l=new THREE.SpotLight(color,energy/(4*Math.PI),0,Math.min(Math.PI/2,Math.max(.01,(d.spotSize||Math.PI/3)/2)),THREE.MathUtils.clamp(d.spotBlend||0,0,1),2);
 else if(d?.type==='area'){const size=d.areaSize||[1,1],w=Math.max(.01,size[0]||1),h=Math.max(.01,size[1]||w);l=new THREE.RectAreaLight(color,energy/Math.max(1,w*h*Math.PI),w,h)}
 else l=new THREE.PointLight(color,energy/(4*Math.PI),0,2);
 l.castShadow=!l.isRectAreaLight;
 if(l.isDirectionalLight||l.isSpotLight){const t=new THREE.Object3D();t.position.set(0,0,-5);t.userData.editorHelper=true;l.add(t);l.target=t}
 return l
}
function blendLightHelper(l){if(l.isPointLight)return new THREE.PointLightHelper(l,.3);if(l.isSpotLight)return new THREE.SpotLightHelper(l);if(l.isDirectionalLight)return new THREE.DirectionalLightHelper(l,.7);if(l.isRectAreaLight){const h=new RectAreaLightHelper(l);l.add(h);return h}return null}
function blendCamera(d){if(d?.type==='orthographic'){const hh=Math.max(.01,(d.orthoScale||10)/2),ww=hh*1.777;return new THREE.OrthographicCamera(-ww,ww,hh,-hh,Math.max(.001,d.clipStart||.1),Math.max(1,d.clipEnd||1000))}const lens=Math.max(.1,d?.lens||50),sensor=Math.max(.1,d?.sensorHeight||24),fov=THREE.MathUtils.radToDeg(2*Math.atan(sensor/(2*lens)));return new THREE.PerspectiveCamera(fov,1.777,Math.max(.001,d?.clipStart||.1),Math.max(1,d?.clipEnd||1000))}
async function importBlendProject(f){
 const oldStatus=$('#statusText').textContent;status('Loading Blender parser…');toast('Opening '+f.name+'…');
 try{
  if(f.size>250*1024*1024&&!confirm('This .blend file is over 250 MB and may use a lot of memory on a phone. Import it anyway?')){status(oldStatus);return}
  const J=await getBlendParser();status('Parsing '+f.name+'…');await new Promise(r=>requestAnimationFrame(r));const data=J.parseBlend(new Uint8Array(await f.arrayBuffer()));
  const objects=J.extractObjects(data),materials=J.extractMaterials(data),lights=J.extractLights(data),cameras=J.extractCameras(data),scenes=J.extractScenes(data),evaluated=J.evaluateAllMeshes(data),baseMeshes=J.extractMeshes(data),matMap=new Map(materials.map(x=>[x.name,x])),meshMap=new Map(baseMeshes.map(x=>[x.name,x])),lightMap=new Map(lights.map(x=>[x.name,x])),camMap=new Map(cameras.map(x=>[x.name,x])),paths=collectionPathMap(scenes[0]?.rootCollection),created=[];let unsupported=0;
  if(roots().length===1&&roots()[0].name==='Cube'&&state.undo.length<=2){state.selection.clear();state.selected=null;removeOne(roots()[0])}
  for(const ob of objects){let o=null,d=null,kind='empty';
   if(ob.type===1&&(d=evaluated.get(ob.name)||meshMap.get(ob.dataName))){const mats=blendMaterialsFor(d,matMap);o=new THREE.Mesh(blendGeometry(d),mats.length===1?mats[0]:mats);o.castShadow=o.receiveShadow=true;kind='mesh'}
   else if(ob.type===10&&(d=lightMap.get(ob.dataName))){o=blendLight(d);kind='light'}
   else if(ob.type===11&&(d=camMap.get(ob.dataName))){o=blendCamera(d);kind='camera'}
   else{o=new THREE.Group();o.add(new THREE.AxesHelper(.45));kind='empty';if(ob.type!==0)unsupported++}
   o.name=ob.name||('Blender Object '+(created.length+1));o.userData={editable:true,kind,imported:true,source:'blend',blenderType:ob.type,blenderDataName:ob.dataName||'',blenderParent:ob.parentName||'',blenderCollections:paths.get(ob.name)||[],customProperties:safeBlendValue(ob.customProperties||{})};blendTransform(o,ob.worldMatrix);scene.add(o);
   if(kind==='light'){const h=blendLightHelper(o);if(h&&!o.isRectAreaLight){h.userData.editorHelper=true;o.userData.helperUUID=h.uuid;scene.add(h)}}
   if(kind==='camera'){const h=new THREE.CameraHelper(o);h.userData.editorHelper=true;o.userData.helperUUID=h.uuid;scene.add(h)}
   created.push(o)
  }
  if(!created.length)throw new Error('No supported objects found in this Blender project');
  const sc=scenes[0];state.blenderInfo={file:f.name,version:'Blender '+data.header.versionString.replace(/^0?([0-9])([0-9]{2})$/,(_,a,b)=>a+'.'+Number(b)),scene:sc?.name||'Scene',objects:created.length,meshes:baseMeshes.length,materials:materials.length,unsupported,frames:sc?(sc.frameStart+'–'+sc.frameEnd+' @ '+Number(sc.fps.toFixed(3))+' fps'):'—',resolution:sc?(sc.resolutionX+'×'+sc.resolutionY+' @ '+sc.resolutionPercentage+'%'):'—'};
  rememberAllMaterials();applyViewportShading();state.selection=new Set(created);state.selected=created.find(x=>x.userData.kind==='mesh')||created[0];frame();state.selection=new Set([state.selected]);select(state.selected,{add:true});push('Import Blender project');renderOutliner();renderProps();stats();status('Imported '+f.name+' • '+created.length+' objects'+(unsupported?' • '+unsupported+' placeholders':''));toast('Blender project imported');
 }catch(e){console.error('Blend import failed',e);blendParserPromise=null;status('Blender import failed');const msg=String(e?.message||e);if(/version|header|large|dna|blend/i.test(msg))toast('Could not parse .blend — Blender 5.x files are supported');else toast('Blender import failed: '+msg.slice(0,90))}
}
function importModelFile(f){const ext=f.name.split('.').pop().toLowerCase();if(ext==='blend')return importBlendProject(f);const url=URL.createObjectURL(f),done=o=>{o.name=f.name.replace(/\.[^.]+$/,'');o.userData={editable:true,kind:'mesh',imported:true};o.traverse(c=>{if(c.isMesh){c.castShadow=true;c.receiveShadow=true}});scene.add(o);URL.revokeObjectURL(url);o.traverse(rememberMaterial);select(o);applyViewportShading();push('Import');renderOutliner();stats();frame();toast('Imported '+f.name)};if(ext==='glb'||ext==='gltf')new GLTFLoader().load(url,g=>done(g.scene),undefined,e=>importError(e,url));else if(ext==='obj')new OBJLoader().load(url,done,undefined,e=>importError(e,url));else if(ext==='stl')new STLLoader().load(url,g=>done(new THREE.Mesh(g,mat())),undefined,e=>importError(e,url));else{URL.revokeObjectURL(url);toast('Unsupported model file')}}
function importError(e,url){URL.revokeObjectURL(url);console.error(e);toast('Model import failed')}
function importModel(){pick('.blend,.glb,.gltf,.obj,.stl',fs=>importModelFile(fs[0]))}
function firstMaterial(o=state.selected){let m=null;o?.traverse?.(c=>{if(!m&&c.isMesh){rememberMaterial(c);const sm=sourceMaterialOf(c);m=Array.isArray(sm)?sm[0]:sm}});return m}
function handleDrop(fs){const a=[...fs];if(!a.length)return;const b=a.find(f=>/\.blend$/i.test(f.name));if(b)return importBlendProject(b);const p=a.find(f=>/\.(blendweb|json)$/i.test(f.name));if(p)return loadProject(p);const m=a.find(f=>/\.(glb|gltf|obj|stl)$/i.test(f.name));if(m)return importModelFile(m);const im=a.find(f=>f.type.startsWith('image/')),ma=firstMaterial();if(im&&ma)return loadTexture(im,ma);toast('Drop .blend, GLB, GLTF, OBJ, STL, project, or image texture')}
function exportGLB(){const mode=state.shading;restoreSourceMaterials();const g=new THREE.Group();roots().forEach(o=>g.add(o.clone(true)));applyViewportShading(mode);new GLTFExporter().parse(g,r=>dl(new Blob([r],{type:'model/gltf-binary'}),'blendweb-scene.glb'),console.error,{binary:true,onlyVisible:true})}
function exportOBJ(){const mode=state.shading;restoreSourceMaterials();const g=new THREE.Group();roots().forEach(o=>g.add(o.clone(true)));applyViewportShading(mode);dl(new Blob([new OBJExporter().parse(g)],{type:'text/plain'}),'blendweb-scene.obj')}
function exportSTL(){const mode=state.shading;restoreSourceMaterials();const g=new THREE.Group();roots().forEach(o=>g.add(o.clone(true)));applyViewportShading(mode);dl(new Blob([new STLExporter().parse(g,{binary:true})],{type:'model/stl'}),'blendweb-scene.stl')}
async function renderImage(){
 const width=Math.max(64,Math.min(8192,Math.round(state.renderWidth))),height=Math.max(64,Math.min(8192,Math.round(state.renderHeight))),scale=Math.max(1,Math.min(3,Math.round(state.renderScale))),max=renderer.capabilities.maxTextureSize,targetW=Math.min(max,width*scale),targetH=Math.min(max,height*scale);
 const old={w:wrap.clientWidth,h:wrap.clientHeight,pixel:renderer.getPixelRatio(),aspect:camera.aspect,shade:state.shading,bg:scene.background,grid:grid.visible,axes:axes.visible,box:box.visible,transform:transform.getHelper().visible};
 status('Rendering '+targetW+'×'+targetH+'…');applyViewportShading('rendered');grid.visible=false;axes.visible=false;box.visible=false;transform.getHelper().visible=false;editable().forEach(o=>helperFor(o)&&(helperFor(o).visible=false));renderer.setPixelRatio(1);renderer.setSize(targetW,targetH,false);camera.aspect=targetW/targetH;camera.updateProjectionMatrix();if(state.renderTransparent)scene.background=null;renderer.render(scene,camera);
 const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));
 if(blob)dl(blob,'blendweb-render-'+width+'x'+height+'.png');
 renderer.setPixelRatio(old.pixel);renderer.setSize(old.w,old.h,false);camera.aspect=old.aspect;camera.updateProjectionMatrix();scene.background=old.bg;grid.visible=old.grid;axes.visible=old.axes;box.visible=old.box;transform.getHelper().visible=old.transform;editable().forEach(o=>helperFor(o)&&(helperFor(o).visible=true));applyViewportShading(old.shade);status('Render saved');toast('Rendered '+targetW+'×'+targetH)
}
function screenshot(){return renderImage()}

function menu(name){if(name==='file')return[['New Project','Ctrl+N',newProject],['Open BlendWeb Project…','Ctrl+O',()=>pick('.blendweb,.json',fs=>loadProject(fs[0]))],['Save BlendWeb Project','Ctrl+S',saveProject],'sep',['Import Blender Project (.blend)…','',()=>pick('.blend',fs=>importBlendProject(fs[0]))],['Import Model…','',importModel],['Export GLB','',exportGLB],['Export OBJ','',exportOBJ],['Export STL','',exportSTL],'sep',['Save Screenshot','',screenshot]];if(name==='edit')return[['Undo','Ctrl+Z',undo],['Redo','Ctrl+Y',redo],'sep',['Select All','A',selectAll],['Deselect','Alt+A',deselectAll],['Duplicate','Shift+D',duplicate],['Delete','X / Del',remove],['Hide Selected','H',hideSelected],['Unhide All','Alt+H',unhideAll],'sep',['Join Selected Meshes','Ctrl+J',joinSelected],['Apply Transform','Ctrl+A',applyTransforms],['Origin to Geometry','',originToGeometry],['Shade Smooth','',()=>shade(true)],['Shade Flat','',()=>shade(false)]];if(name==='add')return[['Cube','',()=>addPrimitive('Cube')],['Sphere','',()=>addPrimitive('Sphere')],['Cylinder','',()=>addPrimitive('Cylinder')],['Cone','',()=>addPrimitive('Cone')],['Torus','',()=>addPrimitive('Torus')],['Torus Knot','',()=>addPrimitive('Torus Knot')],['Plane','',()=>addPrimitive('Plane')],['Circle','',()=>addPrimitive('Circle')],'sep',['Point Light','',()=>addLight('Point Light')],['Spot Light','',()=>addLight('Spot Light')],['Sun','',()=>addLight('Sun')],['Camera','',addCamera],['Empty','',addEmpty]];return[['Frame Selected','F',frame],['Home View','Home',()=>view('perspective')],'sep',['Front','1',()=>view('front')],['Right','3',()=>view('right')],['Top','7',()=>view('top')]]}
function openMenu(b,n){const l=$('#menuLayer');l.innerHTML='';menu(n).forEach(i=>{if(i==='sep'){const d=document.createElement('div');d.className='menu-separator';l.appendChild(d);return}const x=document.createElement('button');x.className='menu-item';x.innerHTML='<span>'+i[0]+'</span><span class="shortcut">'+i[1]+'</span>';x.onclick=()=>{closeMenu();i[2]()};l.appendChild(x)});const r=b.getBoundingClientRect();l.style.left=Math.min(r.left,innerWidth-215)+'px';l.style.top=(r.bottom+2)+'px';l.classList.remove('hidden');b.classList.add('open')}
function closeMenu(){$('#menuLayer').classList.add('hidden');$$('.menu-btn').forEach(b=>b.classList.remove('open'))}
function showSheet(html,after){$('#bottomSheetContent').innerHTML=html;$('#bottomSheet').classList.remove('hidden');after&&after()}
function addSheet(){showSheet('<div class="section-title">Add Object</div><div class="action-row add-grid"></div>',()=>{['Cube','Sphere','Cylinder','Cone','Torus','Plane','Point Light','Camera','Empty'].forEach(t=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>{hideSheet();t.includes('Light')?addLight(t):t==='Camera'?addCamera():t==='Empty'?addEmpty():addPrimitive(t)};$('.add-grid').appendChild(b)})})}
function hideSheet(){$('#bottomSheet').classList.add('hidden')}
function resize(){const w=wrap.clientWidth,h=wrap.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
new ResizeObserver(resize).observe(wrap);
transform.addEventListener('dragging-changed',e=>{orbit.enabled=!e.value;if(e.value&&state.mode==='edit')beginEditMove();if(!e.value){state.mode==='edit'?(updateVertex(),push(state.editVertices.size>1?'Move vertices':'Move vertex'),refreshEdit()):(changed(),push('Transform'))}});
transform.addEventListener('objectChange',()=>state.mode==='edit'?updateVertex():changed());
canvas.onpointerdown=e=>state.pointer={x:e.clientX,y:e.clientY,moved:false};canvas.onpointermove=e=>{if(Math.hypot(e.clientX-state.pointer.x,e.clientY-state.pointer.y)>5)state.pointer.moved=true};canvas.onpointerup=e=>{if(state.pointer.moved||transform.dragging)return;if(state.mode==='edit'){selectVertex(e.clientX,e.clientY,e.shiftKey||state.multi);return}const r=canvas.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(pointer,camera);const ms=[];editable().forEach(o=>o.traverse(c=>c.isMesh&&ms.push(c)));const h=ray.intersectObjects(ms,true)[0];if(!h)return select(null);let o=h.object;while(o.parent&&!o.userData.editable)o=o.parent;if(o.userData.editable){const add=e.shiftKey||state.multi;select(o,{add,toggle:add})}};
wrap.addEventListener('dragenter',e=>{e.preventDefault();wrap.classList.add('drag-hover')});wrap.addEventListener('dragover',e=>{e.preventDefault();wrap.classList.add('drag-hover')});wrap.addEventListener('dragleave',e=>{if(!wrap.contains(e.relatedTarget))wrap.classList.remove('drag-hover')});wrap.addEventListener('drop',e=>{e.preventDefault();wrap.classList.remove('drag-hover');handleDrop(e.dataTransfer?.files||[])});
$('.tool[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('#modeBtn').onclick=toggleEdit;$('#addCubeQuick').onclick=()=>addPrimitive('Cube');$('#duplicateBtn').onclick=duplicate;$('#deleteBtn').onclick=remove;$('#addObjectBtn').onclick=e=>openMenu(e.currentTarget,'add');$('#snapBtn').onclick=snap;$('#homeView').onclick=()=>view('perspective');$('#multiSelectBtn')?.addEventListener('click',()=>{state.multi=!state.multi;$('#multiSelectBtn').classList.toggle('active',state.multi);toast(state.multi?'Multi-select on':'Multi-select off')});$('#spaceBtn')?.addEventListener('click',toggleSpace);$$('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$('.shade').forEach(b=>b.onclick=()=>applyViewportShading(b.dataset.shading));$$('.menu-btn').forEach(b=>b.onclick=()=>openMenu(b,b.dataset.menu));$('#saveProjectBtn').onclick=saveProject;$('#renderBtn').onclick=screenshot;$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$$('#propertyTabs .tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;$$('#propertyTabs .tab').forEach(x=>x.classList.toggle('active',x===b));renderProps()});$('#mobileAdd').onclick=addSheet;$$('[data-mobile]').forEach(b=>b.onclick=()=>b.dataset.mobile==='outliner'?showSheet('<div class="section-title">Scene Collection</div><div class="sheet-outliner"></div>',()=>renderOutliner($('.sheet-outliner'))):showSheet('<div class="sheet-props"></div>',()=>renderProps($('.sheet-props'),'object')));$('#bottomSheet').onclick=e=>{if(e.target===$('#bottomSheet'))hideSheet()};addEventListener('pointerdown',e=>{if(!e.target.closest('.menu-layer,.menu-btn'))closeMenu()});
addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const c=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(c&&k==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if(c&&k==='y')redo();else if(c&&k==='s'){e.preventDefault();saveProject()}else if(c&&k==='o'){e.preventDefault();pick('.blendweb,.json',fs=>loadProject(fs[0]))}else if(c&&k==='n'){e.preventDefault();newProject()}else if(c&&k==='j'){e.preventDefault();joinSelected()}else if(c&&k==='a'){e.preventDefault();applyTransforms()}else if(e.altKey&&k==='h'){e.preventDefault();unhideAll()}else if(e.altKey&&k==='a'){e.preventDefault();deselectAll()}else if(k==='a'){e.preventDefault();selectAll()}else if(k==='h'){e.preventDefault();hideSelected()}else if(k==='f'){e.preventDefault();frame()}else if(e.key==='Tab'){e.preventDefault();toggleEdit()}else if(e.key==='Delete'||e.key==='Backspace'||k==='x'){e.preventDefault();remove()}else if(e.shiftKey&&k==='d')duplicate();else if(k==='g')setTool('translate');else if(k==='r')setTool('rotate');else if(k==='s')setTool('scale');else if(k==='q')setTool('select');else if(k==='l')toggleSpace();else if(e.key==='1')view('front');else if(e.key==='3')view('right');else if(e.key==='7')view('top')});
let last=performance.now(),frames=0;function animate(now){requestAnimationFrame(animate);orbit.update();if(box.visible)box.update();editable().forEach(o=>helperFor(o)?.update?.());renderer.render(scene,camera);frames++;if(now-last>700){$('#fpsText').textContent=Math.round(frames*1000/(now-last))+' FPS';frames=0;last=now}}
(function init(){const raw=localStorage.getItem('blendweb-autosave');if(raw){try{restore(JSON.parse(raw));toast('Restored autosave')}catch(e){console.warn('Autosave restore failed',e);localStorage.removeItem('blendweb-autosave')}}if(!editable().length)addPrimitive('Cube',{name:'Cube',position:[0,1,0]});rememberAllMaterials();applyViewportShading('solid');state.undo=[];state.redo=[];push('Initial scene');setTool('translate');renderOutliner();renderProps();stats();resize();window.__BLENDWEB_READY__=true;animate(performance.now());if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})})();
