import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OBJLoader} from 'three/addons/loaders/OBJLoader.js';
import {STLLoader} from 'three/addons/loaders/STLLoader.js';
import {GLTFExporter} from 'three/addons/exporters/GLTFExporter.js';
import {OBJExporter} from 'three/addons/exporters/OBJExporter.js';
import {STLExporter} from 'three/addons/exporters/STLExporter.js';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const canvas=$('#viewport'), wrap=$('#viewportWrap'), outliner=$('#outliner'), props=$('#propertiesContent'), input=$('#fileInput');
const state={selected:null,tool:'translate',mode:'object',tab:'object',snap:false,shading:'material',counter:1,bg:'#2b2d31',undo:[],redo:[],historyLock:false,editPoints:null,editHandle:null,editVertex:-1,pointer:{x:0,y:0,moved:false}};
const scene=new THREE.Scene(); scene.background=new THREE.Color(state.bg);
const camera=new THREE.PerspectiveCamera(50,1,.01,5000); camera.position.set(7,5.5,8);
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); renderer.shadowMap.enabled=true; renderer.outputColorSpace=THREE.SRGBColorSpace; renderer.toneMapping=THREE.ACESFilmicToneMapping;
const orbit=new OrbitControls(camera,canvas); orbit.enableDamping=true; orbit.target.set(0,.8,0); orbit.screenSpacePanning=true;
const transform=new TransformControls(camera,canvas); scene.add(transform.getHelper()); transform.getHelper().visible=false;
const grid=new THREE.GridHelper(100,100,0x55575c,0x3b3d42); grid.material.transparent=true; grid.material.opacity=.55; scene.add(grid);
const axes=new THREE.AxesHelper(1.3); axes.position.y=.002; scene.add(axes);
scene.add(new THREE.HemisphereLight(0xffffff,0x30384a,1.65));
const sun=new THREE.DirectionalLight(0xffffff,2.1); sun.position.set(4,8,5); sun.castShadow=true; scene.add(sun);
const box=new THREE.BoxHelper(undefined,0xff9a36); box.visible=false; box.material.depthTest=false; scene.add(box);
const ray=new THREE.Raycaster(), pointer=new THREE.Vector2();
const editable=()=>scene.children.filter(o=>o.userData&&o.userData.editable);
const roots=()=>editable().filter(o=>!o.parent||!o.parent.userData||!o.parent.userData.editable);
const mat=(c='#9aa0a8')=>new THREE.MeshStandardMaterial({color:c,roughness:.55,metalness:.05});
const toast=m=>{let t=$('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),1400)};
const status=m=>$('#statusText').textContent=m;
const dl=(b,n)=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};

function helperFor(o){return o&&o.userData.helperUUID?scene.getObjectByProperty('uuid',o.userData.helperUUID):null}
function addPrimitive(type,opt={}){
 let g; if(type==='Sphere')g=new THREE.SphereGeometry(1.2,32,20);else if(type==='Cylinder')g=new THREE.CylinderGeometry(1,1,2.3,32);else if(type==='Cone')g=new THREE.ConeGeometry(1.2,2.5,32);else if(type==='Torus')g=new THREE.TorusGeometry(1.25,.38,18,48);else if(type==='Torus Knot')g=new THREE.TorusKnotGeometry(1,.3,96,14);else if(type==='Plane')g=new THREE.PlaneGeometry(3,3,8,8);else if(type==='Circle')g=new THREE.CircleGeometry(1.5,48);else g=new THREE.BoxGeometry(2,2,2);
 const o=new THREE.Mesh(g,mat(opt.color||'#9aa0a8')); o.name=opt.name||type+'.'+String(state.counter++).padStart(3,'0'); o.userData={editable:true,kind:'mesh'}; o.castShadow=type!=='Plane'&&type!=='Circle';o.receiveShadow=true;if(type==='Plane'||type==='Circle')o.rotation.x=-Math.PI/2;o.position.copy(orbit.target);if(opt.position)o.position.fromArray(opt.position);scene.add(o);select(o);push('Add '+type);renderOutliner();stats();return o
}
function addLight(type){
 let l=type==='Point Light'?new THREE.PointLight(0xffffff,30,25,2):type==='Spot Light'?new THREE.SpotLight(0xffffff,45,35,Math.PI/5,.35,2):new THREE.DirectionalLight(0xffffff,2);
 l.name=type+'.'+String(state.counter++).padStart(3,'0');l.position.copy(camera.position).lerp(orbit.target,.35);l.userData={editable:true,kind:'light'};l.castShadow=true;scene.add(l);
 const h=type==='Point Light'?new THREE.PointLightHelper(l,.3):type==='Spot Light'?new THREE.SpotLightHelper(l):new THREE.DirectionalLightHelper(l,.7);h.userData.editorHelper=true;l.userData.helperUUID=h.uuid;scene.add(h);select(l);push('Add '+type);renderOutliner();stats()
}
function addEmpty(){const o=new THREE.Group();o.name='Empty.'+String(state.counter++).padStart(3,'0');o.userData={editable:true,kind:'empty'};o.position.copy(orbit.target);o.add(new THREE.AxesHelper(.65));scene.add(o);select(o);push('Add Empty');renderOutliner();stats()}
function addCamera(){const o=new THREE.PerspectiveCamera(50,1.777,.1,100);o.name='Camera.'+String(state.counter++).padStart(3,'0');o.userData={editable:true,kind:'camera'};o.position.copy(camera.position);o.quaternion.copy(camera.quaternion);scene.add(o);const h=new THREE.CameraHelper(o);h.userData.editorHelper=true;o.userData.helperUUID=h.uuid;scene.add(h);select(o);push('Add Camera');renderOutliner();stats()}

function select(o){
 if(state.mode==='edit'&&o!==state.selected)exitEdit(false);state.selected=o||null;
 if(o){transform.attach(o);transform.getHelper().visible=state.tool!=='select';box.setFromObject(o);box.visible=state.mode==='object'&&o.userData.kind==='mesh';status('Selected '+o.name)}
 else{transform.detach();transform.getHelper().visible=false;box.visible=false}
 renderOutliner();renderProps()
}
function icon(o){return o.userData.kind==='light'?'✦':o.userData.kind==='camera'?'△':o.userData.kind==='empty'?'⌗':'◆'}
function renderOutliner(target=outliner){
 target.innerHTML='';roots().forEach(o=>{const r=document.createElement('div');r.className='outliner-row'+(o===state.selected?' selected':'');r.innerHTML='<span class="type">'+icon(o)+'</span><span class="name"></span><button class="visibility">'+(o.visible?'◉':'○')+'</button>';$('.name',r).textContent=o.name;r.onclick=e=>{if(!e.target.closest('.visibility'))select(o)};$('.visibility',r).onclick=e=>{e.stopPropagation();o.visible=!o.visible;e.currentTarget.textContent=o.visible?'◉':'○'};target.appendChild(r)});
 if(!target.children.length)target.innerHTML='<div class="empty-state">Scene is empty.<br>Use <b>＋ Add</b>.</div>'
}
function xyz(title,v,cb,step=.01){const s=document.createElement('div');s.className='section';s.innerHTML='<div class="section-title">'+title+'</div><div class="xyz-row"></div>';['x','y','z'].forEach((a,i)=>{const l=document.createElement('label');l.className='xyz-field '+a;l.innerHTML='<span>'+a.toUpperCase()+'</span><input type="number" step="'+step+'" value="'+Number(v[i].toFixed(4))+'">';$('input',l).onchange=e=>cb(i,+e.target.value);$('.xyz-row',s).appendChild(l)});return s}
function renderProps(target=props,tab=state.tab){
 target.innerHTML='';if(tab==='scene'){renderScene(target);return}const o=state.selected;if(!o){target.innerHTML='<div class="empty-state">Select an object.</div>';return}
 if(tab==='material'){renderMaterial(target,o);return}
 const a=document.createElement('div');a.className='section';a.innerHTML='<div class="section-title">Object</div><label class="field-row"><span>Name</span><input class="nm"></label><div class="action-row"><button class="frame">Frame Selected</button><button class="dup">Duplicate</button></div>';$('.nm',a).value=o.name;$('.nm',a).onchange=e=>{o.name=e.target.value||'Object';renderOutliner();push('Rename')};$('.frame',a).onclick=frame;$('.dup',a).onclick=duplicate;target.appendChild(a);
 target.appendChild(xyz('Location',o.position.toArray(),(i,v)=>{o.position.setComponent(i,v);changed()}));
 target.appendChild(xyz('Rotation',[o.rotation.x,o.rotation.y,o.rotation.z].map(THREE.MathUtils.radToDeg),(i,v)=>{o.rotation[['x','y','z'][i]]=THREE.MathUtils.degToRad(v);changed()},.1));
 target.appendChild(xyz('Scale',o.scale.toArray(),(i,v)=>{o.scale.setComponent(i,v);changed()}));
 if(o.userData.kind==='light'){const s=document.createElement('div');s.className='section';s.innerHTML='<div class="section-title">Light</div><label class="field-row"><span>Color</span><input class="lc" type="color" value="#'+o.color.getHexString()+'"></label><label class="field-row"><span>Intensity</span><input class="li" type="number" step=".1" value="'+o.intensity+'"></label>';$('.lc',s).oninput=e=>o.color.set(e.target.value);$('.li',s).onchange=e=>o.intensity=+e.target.value;target.appendChild(s)}
}
function renderMaterial(target,o){let m; o.traverse(c=>{if(!m&&c.isMesh)m=Array.isArray(c.material)?c.material[0]:c.material});if(!m){target.innerHTML='<div class="empty-state">No mesh material.</div>';return}const s=document.createElement('div');s.className='section';s.innerHTML='<div class="section-title">Surface</div><label class="field-row"><span>Base Color</span><input class="c" type="color" value="#'+(m.color?m.color.getHexString():'ffffff')+'"></label><label class="field-row"><span>Metallic</span><input class="metal" type="range" min="0" max="1" step=".01" value="'+(m.metalness||0)+'"></label><label class="field-row"><span>Roughness</span><input class="rough" type="range" min="0" max="1" step=".01" value="'+(m.roughness==null?.5:m.roughness)+'"></label><label class="field-row"><span>Opacity</span><input class="alpha" type="range" min=".05" max="1" step=".01" value="'+(m.opacity||1)+'"></label><label class="checkbox-row"><input class="wire" type="checkbox" '+(m.wireframe?'checked':'')+'> Wireframe</label>';$('.c',s).oninput=e=>m.color&&m.color.set(e.target.value);$('.metal',s).oninput=e=>{if('metalness'in m)m.metalness=+e.target.value};$('.rough',s).oninput=e=>{if('roughness'in m)m.roughness=+e.target.value};$('.alpha',s).oninput=e=>{m.opacity=+e.target.value;m.transparent=m.opacity<1};$('.wire',s).onchange=e=>m.wireframe=e.target.checked;target.appendChild(s);const t=document.createElement('div');t.className='section';t.innerHTML='<div class="section-title">Texture</div><button class="wide-btn tex">Load Image Texture…</button><div style="height:5px"></div><button class="wide-btn clear">Clear Texture</button>';$('.tex',t).onclick=()=>pick('image/*',fs=>loadTexture(fs[0],m));$('.clear',t).onclick=()=>{m.map=null;m.needsUpdate=true};target.appendChild(t)}
function renderScene(target){const s=document.createElement('div');s.className='section';s.innerHTML='<div class="section-title">World</div><label class="field-row"><span>Background</span><input class="bg" type="color" value="'+state.bg+'"></label><label class="field-row"><span>Exposure</span><input class="ex" type="number" step=".05" value="'+renderer.toneMappingExposure+'"></label><label class="checkbox-row"><input class="gr" type="checkbox" '+(grid.visible?'checked':'')+'> Show grid</label>';$('.bg',s).oninput=e=>{state.bg=e.target.value;scene.background.set(state.bg)};$('.ex',s).onchange=e=>renderer.toneMappingExposure=+e.target.value;$('.gr',s).onchange=e=>grid.visible=e.target.checked;target.appendChild(s);const p=document.createElement('div');p.className='section';p.innerHTML='<div class="section-title">Project</div><div class="action-row"><button class="new">New</button><button class="save">Save File</button><button class="open">Open File</button></div>';$('.new',p).onclick=newProject;$('.save',p).onclick=saveProject;$('.open',p).onclick=()=>pick('.blendweb,.json',fs=>loadProject(fs[0]));target.appendChild(p)}

function enterEdit(){const o=state.selected;if(!o||!o.isMesh||!o.geometry.attributes.position){toast('Select a mesh first');return}state.mode='edit';$('#modeBtn').textContent='Edit Mode ▾';transform.detach();box.visible=false;state.editPoints=new THREE.Points(o.geometry,new THREE.PointsMaterial({color:0xff9a36,size:.09,sizeAttenuation:true,depthTest:false}));state.editPoints.userData.editorHelper=true;o.add(state.editPoints);state.editHandle=new THREE.Object3D();scene.add(state.editHandle);state.editVertex=-1;setTool('translate');status('Edit Mode: tap a vertex')}
function exitEdit(hist=true){if(state.mode!=='edit')return;if(state.editPoints&&state.editPoints.parent)state.editPoints.parent.remove(state.editPoints);if(state.editHandle)scene.remove(state.editHandle);state.editPoints=null;state.editHandle=null;state.editVertex=-1;state.mode='object';$('#modeBtn').textContent='Object Mode ▾';if(state.selected)select(state.selected);if(hist)push('Edit mesh')}
function toggleEdit(){state.mode==='edit'?exitEdit():enterEdit()}
function selectVertex(x,y){const o=state.selected;if(!o||!state.editPoints)return;const r=canvas.getBoundingClientRect();pointer.x=((x-r.left)/r.width)*2-1;pointer.y=-((y-r.top)/r.height)*2+1;ray.setFromCamera(pointer,camera);ray.params.Points.threshold=Math.max(.06,camera.position.distanceTo(orbit.target)*.008);const h=ray.intersectObject(state.editPoints,false)[0];if(!h)return;state.editVertex=h.index;const a=o.geometry.attributes.position;const local=new THREE.Vector3().fromBufferAttribute(a,h.index);state.editHandle.position.copy(o.localToWorld(local));transform.attach(state.editHandle);transform.setMode('translate');transform.getHelper().visible=true;status('Vertex '+h.index+' selected')}
function updateVertex(){if(state.mode!=='edit'||state.editVertex<0)return;const o=state.selected,p=o.worldToLocal(state.editHandle.position.clone()),a=o.geometry.attributes.position;a.setXYZ(state.editVertex,p.x,p.y,p.z);a.needsUpdate=true;o.geometry.computeVertexNormals();o.geometry.computeBoundingSphere()}

function setTool(t){state.tool=t;$$('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===t));if(t==='select'){transform.detach();transform.getHelper().visible=false}else if(state.mode==='edit'){if(state.editVertex>=0){transform.attach(state.editHandle);transform.setMode('translate');transform.getHelper().visible=true}}else if(state.selected){transform.attach(state.selected);transform.setMode(t);transform.getHelper().visible=true}$('#transformModeText').textContent=state.mode==='edit'?'Vertex Edit':t[0].toUpperCase()+t.slice(1)}
function changed(){box.update();helperFor(state.selected)?.update?.();renderProps();debouncedPush()}
let ht;function debouncedPush(){clearTimeout(ht);ht=setTimeout(()=>push('Transform'),220)}
function snap(){state.snap=!state.snap;$('#snapBtn').classList.toggle('active',state.snap);transform.setTranslationSnap(state.snap?.25:null);transform.setRotationSnap(state.snap?THREE.MathUtils.degToRad(15):null);transform.setScaleSnap(state.snap?.1:null)}
function view(v){const t=orbit.target.clone(),d=Math.max(6,camera.position.distanceTo(t));if(v==='top')camera.position.set(t.x,t.y+d,t.z+.001);else if(v==='front')camera.position.set(t.x,t.y,t.z+d);else if(v==='right')camera.position.set(t.x+d,t.y,t.z);else camera.position.set(t.x+d*.7,t.y+d*.5,t.z+d*.8);camera.lookAt(t);orbit.update()}
function frame(){if(!state.selected)return;const b=new THREE.Box3().setFromObject(state.selected),c=b.getCenter(new THREE.Vector3()),s=b.getSize(new THREE.Vector3()).length()||2,d=camera.position.clone().sub(orbit.target).normalize();orbit.target.copy(c);camera.position.copy(c).add(d.multiplyScalar(Math.max(2.5,s*1.7)));orbit.update()}
function stats(){let v=0;editable().forEach(o=>o.traverse(c=>{if(c.isMesh)v+=c.geometry.attributes.position?.count||0}));$('#sceneStats').textContent=editable().length+' objects • '+v.toLocaleString()+' verts'}
function duplicate(){if(!state.selected)return;const c=state.selected.clone(true);c.name=state.selected.name.replace(/\.\d+$/,'')+'.'+String(state.counter++).padStart(3,'0');c.position.x+=.5;c.userData={...state.selected.userData,editable:true};delete c.userData.helperUUID;scene.add(c);select(c);push('Duplicate');renderOutliner();stats()}
function remove(){if(!state.selected)return;const n=state.selected.name, h=helperFor(state.selected);if(h)scene.remove(h);scene.remove(state.selected);select(null);push('Delete '+n);renderOutliner();stats()}

function project(){return{app:'BlendWeb',version:1,scene:roots().map(o=>o.toJSON()),camera:{position:camera.position.toArray(),target:orbit.target.toArray()},world:{background:state.bg,exposure:renderer.toneMappingExposure,grid:grid.visible}}}
function restore(data,hist=false){state.historyLock=true;try{if(state.mode==='edit')exitEdit(false);select(null);roots().forEach(o=>scene.remove(o));const loader=new THREE.ObjectLoader();(data.scene||[]).forEach(j=>{const o=loader.parse(j);o.userData.editable=true;o.traverse(c=>{if(c.isMesh){c.castShadow=true;c.receiveShadow=true}});scene.add(o)});if(data.camera){camera.position.fromArray(data.camera.position);orbit.target.fromArray(data.camera.target)}if(data.world){state.bg=data.world.background||state.bg;scene.background.set(state.bg);renderer.toneMappingExposure=data.world.exposure||1;grid.visible=data.world.grid!==false}renderOutliner();renderProps();stats();orbit.update()}finally{state.historyLock=false}if(hist)push('Open project')}
function push(label){if(state.historyLock)return;const d=JSON.stringify(project());if(state.undo.at(-1)?.data===d)return;state.undo.push({label,data:d});if(state.undo.length>30)state.undo.shift();state.redo=[];localStorage.setItem('blendweb-autosave',d);buttons()}
function buttons(){$('#undoBtn').disabled=state.undo.length<2;$('#redoBtn').disabled=!state.redo.length}
function undo(){if(state.undo.length<2)return;state.redo.push(state.undo.pop());restore(JSON.parse(state.undo.at(-1).data));buttons()}
function redo(){const n=state.redo.pop();if(!n)return;state.undo.push(n);restore(JSON.parse(n.data));buttons()}
function saveProject(){dl(new Blob([JSON.stringify(project(),null,2)],{type:'application/json'}),'project.blendweb')}
function loadProject(f){const r=new FileReader();r.onload=()=>{try{restore(JSON.parse(r.result),true);toast('Project opened')}catch(e){console.error(e);toast('Open failed')}};r.readAsText(f)}
function newProject(){if(editable().length&&!confirm('Clear the current scene?'))return;roots().forEach(o=>scene.remove(o));state.undo=[];state.redo=[];const c=addPrimitive('Cube',{name:'Cube',position:[0,1,0]});select(c);push('New project');frame()}
function pick(accept,fn,m=false){input.value='';input.accept=accept;input.multiple=m;input.onchange=()=>input.files?.length&&fn([...input.files]);input.click()}
function loadTexture(f,m){const r=new FileReader();r.onload=()=>new THREE.TextureLoader().load(r.result,t=>{t.colorSpace=THREE.SRGBColorSpace;m.map=t;m.needsUpdate=true});r.readAsDataURL(f)}
function importModel(){pick('.glb,.gltf,.obj,.stl',fs=>{const f=fs[0],ext=f.name.split('.').pop().toLowerCase(),url=URL.createObjectURL(f),done=o=>{o.name=f.name.replace(/\.[^.]+$/,'');o.userData={editable:true,kind:'mesh',imported:true};o.traverse(c=>{if(c.isMesh){c.castShadow=true;c.receiveShadow=true}});scene.add(o);URL.revokeObjectURL(url);select(o);push('Import');renderOutliner();stats();frame()};if(ext==='glb'||ext==='gltf')new GLTFLoader().load(url,g=>done(g.scene));else if(ext==='obj')new OBJLoader().load(url,done);else new STLLoader().load(url,g=>done(new THREE.Mesh(g,mat())))})}
function exportGLB(){const g=new THREE.Group();roots().forEach(o=>g.add(o.clone(true)));new GLTFExporter().parse(g,r=>dl(new Blob([r],{type:'model/gltf-binary'}),'blendweb-scene.glb'),console.error,{binary:true,onlyVisible:true})}
function exportOBJ(){const g=new THREE.Group();roots().forEach(o=>g.add(o.clone(true)));dl(new Blob([new OBJExporter().parse(g)],{type:'text/plain'}),'blendweb-scene.obj')}
function exportSTL(){const g=new THREE.Group();roots().forEach(o=>g.add(o.clone(true)));dl(new Blob([new STLExporter().parse(g,{binary:true})],{type:'model/stl'}),'blendweb-scene.stl')}
function screenshot(){renderer.render(scene,camera);canvas.toBlob(b=>dl(b,'blendweb-render.png'),'image/png')}

function menu(name){if(name==='file')return[['New Project','Ctrl+N',newProject],['Open Project…','Ctrl+O',()=>pick('.blendweb,.json',fs=>loadProject(fs[0]))],['Save Project','Ctrl+S',saveProject],'sep',['Import Model…','',importModel],['Export GLB','',exportGLB],['Export OBJ','',exportOBJ],['Export STL','',exportSTL],'sep',['Save Screenshot','',screenshot]];if(name==='edit')return[['Undo','Ctrl+Z',undo],['Redo','Ctrl+Y',redo],'sep',['Duplicate','Shift+D',duplicate],['Delete','Del',remove]];if(name==='add')return[['Cube','',()=>addPrimitive('Cube')],['Sphere','',()=>addPrimitive('Sphere')],['Cylinder','',()=>addPrimitive('Cylinder')],['Cone','',()=>addPrimitive('Cone')],['Torus','',()=>addPrimitive('Torus')],['Torus Knot','',()=>addPrimitive('Torus Knot')],['Plane','',()=>addPrimitive('Plane')],['Circle','',()=>addPrimitive('Circle')],'sep',['Point Light','',()=>addLight('Point Light')],['Spot Light','',()=>addLight('Spot Light')],['Sun','',()=>addLight('Sun')],['Camera','',addCamera],['Empty','',addEmpty]];return[['Frame Selected','',frame],['Home View','Home',()=>view('perspective')],'sep',['Front','1',()=>view('front')],['Right','3',()=>view('right')],['Top','7',()=>view('top')]]}
function openMenu(b,n){const l=$('#menuLayer');l.innerHTML='';menu(n).forEach(i=>{if(i==='sep'){const d=document.createElement('div');d.className='menu-separator';l.appendChild(d);return}const x=document.createElement('button');x.className='menu-item';x.innerHTML='<span>'+i[0]+'</span><span class="shortcut">'+i[1]+'</span>';x.onclick=()=>{closeMenu();i[2]()};l.appendChild(x)});const r=b.getBoundingClientRect();l.style.left=Math.min(r.left,innerWidth-215)+'px';l.style.top=(r.bottom+2)+'px';l.classList.remove('hidden');b.classList.add('open')}
function closeMenu(){$('#menuLayer').classList.add('hidden');$$('.menu-btn').forEach(b=>b.classList.remove('open'))}
function showSheet(html,after){$('#bottomSheetContent').innerHTML=html;$('#bottomSheet').classList.remove('hidden');after&&after()}
function addSheet(){showSheet('<div class="section-title">Add Object</div><div class="action-row add-grid"></div>',()=>{['Cube','Sphere','Cylinder','Cone','Torus','Plane','Point Light','Camera','Empty'].forEach(t=>{const b=document.createElement('button');b.textContent=t;b.onclick=()=>{hideSheet();t.includes('Light')?addLight(t):t==='Camera'?addCamera():t==='Empty'?addEmpty():addPrimitive(t)};$('.add-grid').appendChild(b)})})}
function hideSheet(){$('#bottomSheet').classList.add('hidden')}
function resize(){const w=wrap.clientWidth,h=wrap.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
new ResizeObserver(resize).observe(wrap);
transform.addEventListener('dragging-changed',e=>{orbit.enabled=!e.value;if(!e.value){state.mode==='edit'?(updateVertex(),push('Move vertex')):(changed(),push('Transform'))}});
transform.addEventListener('objectChange',()=>state.mode==='edit'?updateVertex():changed());
canvas.onpointerdown=e=>state.pointer={x:e.clientX,y:e.clientY,moved:false};canvas.onpointermove=e=>{if(Math.hypot(e.clientX-state.pointer.x,e.clientY-state.pointer.y)>5)state.pointer.moved=true};canvas.onpointerup=e=>{if(state.pointer.moved||transform.dragging)return;if(state.mode==='edit'){selectVertex(e.clientX,e.clientY);return}const r=canvas.getBoundingClientRect();pointer.x=((e.clientX-r.left)/r.width)*2-1;pointer.y=-((e.clientY-r.top)/r.height)*2+1;ray.setFromCamera(pointer,camera);const ms=[];editable().forEach(o=>o.traverse(c=>c.isMesh&&ms.push(c)));const h=ray.intersectObjects(ms,true)[0];if(!h)return select(null);let o=h.object;while(o.parent&&!o.userData.editable)o=o.parent;if(o.userData.editable)select(o)};
$$('.tool[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));$('#modeBtn').onclick=toggleEdit;$('#addCubeQuick').onclick=()=>addPrimitive('Cube');$('#duplicateBtn').onclick=duplicate;$('#deleteBtn').onclick=remove;$('#addObjectBtn').onclick=e=>openMenu(e.currentTarget,'add');$('#snapBtn').onclick=snap;$('#homeView').onclick=()=>view('perspective');$$('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('.shade').forEach(b=>b.onclick=()=>{$$('.shade').forEach(x=>x.classList.toggle('active',x===b));const mode=b.dataset.shading;editable().forEach(o=>o.traverse(c=>{if(!c.isMesh)return;if(!c.userData.orig)c.userData.orig=c.material;if(mode==='wire')c.material=new THREE.MeshBasicMaterial({color:0xb7bcc6,wireframe:true});else if(mode==='solid')c.material=new THREE.MeshStandardMaterial({color:0x9ba0a8,roughness:.7});else c.material=c.userData.orig}))});$$('.menu-btn').forEach(b=>b.onclick=()=>openMenu(b,b.dataset.menu));$('#saveProjectBtn').onclick=saveProject;$('#renderBtn').onclick=screenshot;$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$$('#propertyTabs .tab').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;$$('#propertyTabs .tab').forEach(x=>x.classList.toggle('active',x===b));renderProps()});$('#mobileAdd').onclick=addSheet;$$('[data-mobile]').forEach(b=>b.onclick=()=>b.dataset.mobile==='outliner'?showSheet('<div class="section-title">Scene Collection</div><div class="sheet-outliner"></div>',()=>renderOutliner($('.sheet-outliner'))):showSheet('<div class="sheet-props"></div>',()=>renderProps($('.sheet-props'),'object')));$('#bottomSheet').onclick=e=>{if(e.target===$('#bottomSheet'))hideSheet()};addEventListener('pointerdown',e=>{if(!e.target.closest('.menu-layer,.menu-btn'))closeMenu()});
addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const c=e.ctrlKey||e.metaKey,k=e.key.toLowerCase();if(c&&k==='z'){e.preventDefault();e.shiftKey?redo():undo()}else if(c&&k==='y')redo();else if(c&&k==='s'){e.preventDefault();saveProject()}else if(c&&k==='o'){e.preventDefault();pick('.blendweb,.json',fs=>loadProject(fs[0]))}else if(e.key==='Tab'){e.preventDefault();toggleEdit()}else if(e.key==='Delete'||e.key==='Backspace')remove();else if(e.shiftKey&&k==='d')duplicate();else if(k==='g')setTool('translate');else if(k==='r')setTool('rotate');else if(k==='s')setTool('scale');else if(k==='q')setTool('select');else if(e.key==='1')view('front');else if(e.key==='3')view('right');else if(e.key==='7')view('top')});
let last=performance.now(),frames=0;function animate(now){requestAnimationFrame(animate);orbit.update();if(box.visible)box.update();editable().forEach(o=>helperFor(o)?.update?.());renderer.render(scene,camera);frames++;if(now-last>700){$('#fpsText').textContent=Math.round(frames*1000/(now-last))+' FPS';frames=0;last=now}}
(function init(){const raw=localStorage.getItem('blendweb-autosave');if(raw){try{restore(JSON.parse(raw));toast('Restored autosave')}catch{}}if(!editable().length)addPrimitive('Cube',{name:'Cube',position:[0,1,0]});state.undo=[];state.redo=[];push('Initial scene');setTool('translate');renderOutliner();renderProps();stats();resize();animate(performance.now());if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{})})();
